-- THIS FILE ONLY CREATES THE DATABASE RUN 'run npm seed' AFTER RUNNING THIS TO GET SCHEMA AND TEST DATA

-- DROP DATABASE
DROP DATABASE IF EXISTS sql12727716;

-- CREATE DATABASE
CREATE DATABASE sql12727716;
